//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfficiencyClassWebAPI.ResourceFiles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Message {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EfficiencyClassWebAPI.ResourceFiles.Message", typeof(Message).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CO2 range of the common market already exixts..
        /// </summary>
        internal static string CO2RangeDuplicatemsg {
            get {
                return ResourceManager.GetString("CO2RangeDuplicatemsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range already exists.
        /// </summary>
        internal static string EfficiencyRangeDuplicatemsg {
            get {
                return ResourceManager.GetString("EfficiencyRangeDuplicatemsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formula already exists..
        /// </summary>
        internal static string FormulaDuplicatemsg {
            get {
                return ResourceManager.GetString("FormulaDuplicatemsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market Details already exist.
        /// </summary>
        internal static string MarketDuplicatemsg {
            get {
                return ResourceManager.GetString("MarketDuplicatemsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModelYear already exists.
        /// </summary>
        internal static string ModelYearDuplicatemsg {
            get {
                return ResourceManager.GetString("ModelYearDuplicatemsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PNO12 details already exists.
        /// </summary>
        internal static string PNO12Duplicatemsg {
            get {
                return ResourceManager.GetString("PNO12Duplicatemsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The same combination of weight and segment co2 exists for this pno12 identifier..
        /// </summary>
        internal static string segmentco2Duplicatemsg {
            get {
                return ResourceManager.GetString("segmentco2Duplicatemsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Super User cannot be added as a Market User.
        /// </summary>
        internal static string SuperUserDuplicatemsg {
            get {
                return ResourceManager.GetString("SuperUserDuplicatemsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already exists..
        /// </summary>
        internal static string UserDuplicatemsg {
            get {
                return ResourceManager.GetString("UserDuplicatemsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable already exists.
        /// </summary>
        internal static string VariableDuplicatemsg {
            get {
                return ResourceManager.GetString("VariableDuplicatemsg", resourceCulture);
            }
        }
    }
}
