//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfficiencyClassWebAPI.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class efficiencyclassdevEntities : DbContext
    {
        public efficiencyclassdevEntities()
            : base("name=efficiencyclassdevEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CommonCo2Range_old> CommonCo2Range_old { get; set; }
        public virtual DbSet<EfficiencyClassRange> EfficiencyClassRanges { get; set; }
        public virtual DbSet<Formula> Formulae { get; set; }
        public virtual DbSet<FormulaDependencyDetail> FormulaDependencyDetails { get; set; }
        public virtual DbSet<FuelTypeConversionvalue> FuelTypeConversionvalues { get; set; }
        public virtual DbSet<Market> Markets { get; set; }
        public virtual DbSet<Market2MarketTypeParameterGroup> Market2MarketTypeParameterGroup { get; set; }
        public virtual DbSet<MarketType> MarketTypes { get; set; }
        public virtual DbSet<ParameterGroupMaster> ParameterGroupMasters { get; set; }
        public virtual DbSet<RangeValue_old> RangeValue_old { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<SpecMarketCO2Range_old> SpecMarketCO2Range_old { get; set; }
        public virtual DbSet<SpecMarketFuelTypeRange_old> SpecMarketFuelTypeRange_old { get; set; }
        public virtual DbSet<StagedEfficiencyClassRange> StagedEfficiencyClassRanges { get; set; }
        public virtual DbSet<StagedFormula> StagedFormulas { get; set; }
        public virtual DbSet<StagedFormulaDependencyDetail> StagedFormulaDependencyDetails { get; set; }
        public virtual DbSet<StagedVariable> StagedVariables { get; set; }
        public virtual DbSet<StagedWeightSegmentCo2> StagedWeightSegmentCo2 { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<UserDetail> UserDetails { get; set; }
        public virtual DbSet<UserMarket> UserMarkets { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<Variable> Variables { get; set; }
        public virtual DbSet<VariableType> VariableTypes { get; set; }
        public virtual DbSet<WeightSegmentCo2> WeightSegmentCo2 { get; set; }
        public virtual DbSet<EfficiencyClassRangeold> EfficiencyClassRangeolds { get; set; }
        public virtual DbSet<Market2MarketTypeParameterGroup_old> Market2MarketTypeParameterGroup_old { get; set; }
    }
}
