//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfficiencyClassWebAPI.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class EfficiencyClassRange
    {
        public long Id { get; set; }
        public Nullable<int> VariableTypeId { get; set; }
        public long MMID { get; set; }
        public decimal StartRange { get; set; }
        public decimal EndRange { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string ECValue { get; set; }
    
        public virtual Market2MarketTypeParameterGroup Market2MarketTypeParameterGroup { get; set; }
        public virtual VariableType VariableType { get; set; }
    }
}
