//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfficiencyClassWebAPI.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Market2MarketTypeParameterGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Market2MarketTypeParameterGroup()
        {
            this.CommonCo2Range_old = new HashSet<CommonCo2Range_old>();
            this.EfficiencyClassRanges = new HashSet<EfficiencyClassRange>();
            this.Formulae = new HashSet<Formula>();
            this.StagedEfficiencyClassRanges = new HashSet<StagedEfficiencyClassRange>();
            this.StagedFormulas = new HashSet<StagedFormula>();
            this.StagedVariables = new HashSet<StagedVariable>();
            this.StagedWeightSegmentCo2 = new HashSet<StagedWeightSegmentCo2>();
            this.SpecMarketCO2Range_old = new HashSet<SpecMarketCO2Range_old>();
            this.SpecMarketFuelTypeRange_old = new HashSet<SpecMarketFuelTypeRange_old>();
            this.Variables = new HashSet<Variable>();
            this.WeightSegmentCo2 = new HashSet<WeightSegmentCo2>();
        }
    
        public long MMId { get; set; }
        public int MarketId { get; set; }
        public int MarketTypeId { get; set; }
        public int MYear { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> ParameterGroupId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommonCo2Range_old> CommonCo2Range_old { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EfficiencyClassRange> EfficiencyClassRanges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Formula> Formulae { get; set; }
        public virtual Market Market { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StagedEfficiencyClassRange> StagedEfficiencyClassRanges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StagedFormula> StagedFormulas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StagedVariable> StagedVariables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StagedWeightSegmentCo2> StagedWeightSegmentCo2 { get; set; }
        public virtual MarketType MarketType { get; set; }
        public virtual ParameterGroupMaster ParameterGroupMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SpecMarketCO2Range_old> SpecMarketCO2Range_old { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SpecMarketFuelTypeRange_old> SpecMarketFuelTypeRange_old { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Variable> Variables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WeightSegmentCo2> WeightSegmentCo2 { get; set; }
    }
}
