//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfficiencyClassWebAPI.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecMarketFuelTypeRange_old
    {
        public long Id { get; set; }
        public int VariableTypeId { get; set; }
        public long MMID { get; set; }
        public string StartRange { get; set; }
        public string EndRange { get; set; }
        public Nullable<int> ValueId { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual Market2MarketTypeParameterGroup Market2MarketTypeParameterGroup { get; set; }
        public virtual RangeValue_old RangeValue_old { get; set; }
        public virtual VariableType VariableType { get; set; }
    }
}
