//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfficiencyClassWebAPI.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMarket
    {
        public int UserId { get; set; }
        public int MarketId { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual Market Market { get; set; }
        public virtual UserDetail UserDetail { get; set; }
    }
}
